Indexing and Sorting

In [4]:
import numpy as np

In [5]:
arr=np.array([2,1,4,5,3])

In [6]:
print(np.sort(arr))

[1 2 3 4 5]


In [7]:
print(np.argsort(arr))

[1 0 4 2 3]


Sorting Row and Column

In [8]:
arr_1=np.array([[6,3,7,4],[6,7,3,2],[5,0,1,9]])

In [9]:
print(np.sort(arr_1,axis=0))

[[5 0 1 2]
 [6 3 3 4]
 [6 7 7 9]]


In [10]:
print(np.sort(arr_1,axis=1))

[[3 4 6 7]
 [2 3 6 7]
 [0 1 5 9]]


In [11]:
print(np.sort(-arr_1))

[[-7 -6 -4 -3]
 [-7 -6 -3 -2]
 [-9 -5 -1  0]]


Alphabetical Sorting

In [12]:
str_1=np.array(['China','Japan','India'])

In [13]:
print(np.sort(str_1))

['China' 'India' 'Japan']


Lexsorting

In [14]:
#returns an array of integers indices

In [15]:
str_2=np.array([1,2,3])
str_3=np.array(['a','d','b'])

In [16]:
print(np.lexsort((str_2,str_3)))

[0 2 1]


Indexing

2D OPERATION

In [17]:
a2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [18]:
print(a2d[0::,0::4])#row,columns

[[ 1  5]
 [ 6 10]]


In [19]:
print(a2d[0:1,0:2:1])

[[1 2]]


3D OPERATION

In [20]:
a3d=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])

In [21]:
print(a3d[0:1:,0::,0::4]) #frame,row,column

[[[ 1  5]
  [ 6 10]]]


In [22]:
print(a3d[0::,::,0::4])

[[[ 1  5]
  [ 6 10]]

 [[11 15]
  [16 20]]]


In [23]:
import pandas as p

In [24]:
print("a")

a


In [25]:
print(a3d[0::,::,0::4])

[[[ 1  5]
  [ 6 10]]

 [[11 15]
  [16 20]]]
