NUMPY

In [2]:
import numpy as np

In [3]:
b=np.array([2,3,4,10,12,6])
np.sort(b)

array([ 2,  3,  4,  6, 10, 12])

Argument sort

In [4]:
np.argsort(b)

array([0, 1, 2, 5, 3, 4], dtype=int64)

RandomState:Random values

In [5]:
rand=np.random
x=rand.randint(0,20,(2,6,4)) #4-z axis, 6-x axis, 2-y axis
print(x)

[[[ 7  2 10 13]
  [12 17  6 15]
  [13  8  4  7]
  [ 7  8  6 16]
  [ 9  7 13  0]
  [ 5 18  4  8]]

 [[14  8 15 12]
  [ 7  6 14  0]
  [11  9  5 11]
  [12  7  7 18]
  [13  9  6 15]
  [18 12  0  4]]]


In [6]:
np.sort(x,axis=0)#0-column 1-row

array([[[ 7,  2, 10, 12],
        [ 7,  6,  6,  0],
        [11,  8,  4,  7],
        [ 7,  7,  6, 16],
        [ 9,  7,  6,  0],
        [ 5, 12,  0,  4]],

       [[14,  8, 15, 13],
        [12, 17, 14, 15],
        [13,  9,  5, 11],
        [12,  8,  7, 18],
        [13,  9, 13, 15],
        [18, 18,  4,  8]]])

In [7]:
y=[['a','b','c'],
   ['z','y','w'],
   ['t','k','p']],

y_1=np.array(y)
np.sort(y_1)


array([[['a', 'b', 'c'],
        ['w', 'y', 'z'],
        ['k', 'p', 't']]], dtype='<U1')

In [8]:
arr_1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])


In [9]:
#to get 6
print(arr_1[0][1][2])
#to get 12
print(arr_1[1][1][2])
#to get a row
print(arr_1[0][1])
#to get a frame
print(arr_1[0])
#to get two numbers



6
12
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [10]:
print(arr_1[0][0][0:3:2],arr_1[0][1][0:3:2])


[1 3] [4 6]


In [11]:
print(arr_1[0, :, 2])

[3 6]


In [ ]:
print(arr_1[0:1:,0::1,2::-2])#[frame,row,column]

[[[3 1]
  [6 4]]]


In [14]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[::-1])

[[ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [15]:
np.sum(arr)

55

In [16]:
np.min(arr)

1

In [18]:
np.sum(arr,axis=0)

array([ 7,  9, 11, 13, 15])

In [19]:
np.max(arr,axis=0)

array([ 6,  7,  8,  9, 10])

In [ ]:
print(arr_1[0][:0])

[]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])

In [ ]:
print(a[:,0::2])

[[1 3]
 [4 6]]


In [ ]:
a3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [ ]:
print(a3d[::,::,::])

In [5]:
b=np.array([[2,3,4,10,12,6],[2,3,4,5,6,7]])
print(np.ndim(b))

2


In [8]:
print(np.sum(b,axis=0))

[ 4  6  8 15 18 13]
