In [1]:
import numpy as np

In [13]:
x=np.ones((4,4),dtype=float)
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
a=np.array([('bored',2,41.0),('sarrow',3,31.0)],
dtype=([('name',(np.str_,10)),('level',np.int32),('hours',np.float64)]))
print(a)

[('bored', 2, 41.) ('sarrow', 3, 31.)]


In [22]:
b=np.sort(a,order='name')
print("Sorting according to name:",b)

Sorting according to name: [('bored', 2, 41.) ('sarrow', 3, 31.)]


In [24]:
c=np.sort(a,order='hours')
print("Sorting according to hours:",c)

Sorting according to hours: [('sarrow', 3, 31.) ('bored', 2, 41.)]


command data type

In [25]:
data=np.zeros(4,dtype={'names':('name','age','weight'),
                       'formats':('U10','i4','f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [27]:
data=np.zeros(4,dtype={'names':('name','age','weight'),
                       'formats':((np.str_,10),np.int32,np.float32)})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')]


EXAMPLE TABLE

In [35]:
table_1=np.array([(1,"Rohit",'Roti',1200,'sad123','9884511368'),(2,"Rohan",'Chappati',1100,'sad124','988451136'),(3,"Roshan",'Puri',1500,'sad125','9884510368'),(4,"Vijay",'Naan',2200,'sad023','9804511368'),(5,"Suchita",'Sambar',1250,'sad273','9894511368'),(6,"Vivek",'Noodles',3200,'sad13','884511368'),(7,"Shruthi",'Biryani',2360,'sa123','9884571368')],
dtype=([('S.No',np.int64),('NAME',(np.str_,20)),('FOOD',(np.str_,20)),('Calorie',np.int32),('BILL_no',(np.str_,20)),('PHONE',(np.str_,10))]))
print(table_1)

[(1, 'Rohit', 'Roti', 1200, 'sad123', '9884511368')
 (2, 'Rohan', 'Chappati', 1100, 'sad124', '988451136')
 (3, 'Roshan', 'Puri', 1500, 'sad125', '9884510368')
 (4, 'Vijay', 'Naan', 2200, 'sad023', '9804511368')
 (5, 'Suchita', 'Sambar', 1250, 'sad273', '9894511368')
 (6, 'Vivek', 'Noodles', 3200, 'sad13', '884511368')
 (7, 'Shruthi', 'Biryani', 2360, 'sa123', '9884571368')]
